// references/legacy-reader-web/src/components/PdfPage.vue
<template>
  <div><canvas ref="canvas"></canvas></div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import type { PDFDocumentProxy } from '@/pdfjs'

const props = defineProps<{
  source: PDFDocumentProxy
  page: number
  scale?: number
}>()

const emit = defineEmits<{
  rendered: []
  'rendering-failed': [error: unknown]
}>()

const canvas = ref<HTMLCanvasElement>()

async function renderPage() {
  try {
    const pdfPage = await props.source.getPage(props.page)
    const viewport = pdfPage.getViewport({ scale: props.scale ?? 2 })
    const el = canvas.value!
    el.width = viewport.width
    el.height = viewport.height
    await pdfPage.render({ canvasContext: el.getContext('2d')!, viewport }).promise
    emit('rendered')
  } catch (e) {
    console.error('PdfPage render error:', e)
    emit('rendering-failed', e)
  }
}

onMounted(renderPage)
watch(() => [props.source, props.page], renderPage)
</script>

<style>
canvas {
  display: block;
  width: 100% !important;
  height: auto !important;
}
</style>

// packages/pdf-viewer/src/PdfPage.tsx
import { useRef, useEffect, useState } from "react";
import type { PDFDocumentProxy } from "pdfjs-dist";

interface PdfPageProps {
  document: PDFDocumentProxy;
  pageNumber: number;
  scale?: number;
  className?: string;
  onRendered?: (pageNumber: number) => void;
  onError?: (pageNumber: number, error: Error) => void;
}

export function PdfPage({ document, pageNumber, scale = 2, className = "", onRendered, onError }: PdfPageProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [rendering, setRendering] = useState(false);
  const renderTask = useRef<any>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !document) return;

    setRendering(true);

    document.getPage(pageNumber).then((page) => {
      const viewport = page.getViewport({ scale });
      canvas.width = viewport.width;
      canvas.height = viewport.height;
      canvas.style.width = "100%";
      canvas.style.height = "auto";

      const ctx = canvas.getContext("2d")!;
      if (renderTask.current) {
        renderTask.current.cancel();
      }

      renderTask.current = page.render({ canvasContext: ctx, viewport });
      renderTask.current.promise
        .then(() => { setRendering(false); onRendered?.(pageNumber); })
        .catch((err: any) => {
          if (err?.name !== "RenderingCancelledException") {
            setRendering(false);
            onError?.(pageNumber, err);
          }
        });
    }).catch((err) => {
      setRendering(false);
      onError?.(pageNumber, err);
    });

    return () => { renderTask.current?.cancel(); };
  }, [document, pageNumber, scale]);

  return (
    <div className={`relative ${className}`}>
      <canvas ref={canvasRef} />
      {rendering && (
        <div className="absolute inset-0 flex items-center justify-center bg-paper/85">
          <div className="w-4 h-4 border-2 border-red border-t-transparent rounded-full animate-spin" />
        </div>
      )}
    </div>
  );
}
